name: deepparse-artifact
dependencies:
  - python=3.11
  - pip
  - pip:
      - pyyaml==6.0.1
      - click==8.1.7
      - tqdm==4.66.1
      - torch==2.1.2
      - transformers==4.36.2
      - accelerate==0.24.1
      - pytest==7.4.4
      - ruff==0.1.9
