name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: astral-sh/setup-uv@v2
      - run: uv sync
      - run: uv run ruff check deepparse tests
      - run: uv run pytest -q
      - run: |
          ./scripts/prepare_paths.sh
          uv run python -m deepparse.cli synth --dataset DemoTiny --mode offline --out artifacts/masks/DemoTiny.json
          uv run python -m deepparse.cli eval --config configs/demo_small.yaml --deterministic
